name: Test 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]
  #schedule:
  #  - cron: '0 3 * * *' # run at 3 AM UTC
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        default: 'master'

jobs:
  build:
    steps:
      - name: Build
        run: |
          echo Build
  extra:
    
    if: ((github.ref == 'refs/heads/master') || (github.event_name == 'release'))
    needs: build
    steps:
      - name: Upload
        run: |
          echo Upload
  release:
    if: github.event_name == 'release'
    needs: extra
    steps:
      - name: Release
        run: |
          echo Release
